#import "ligo-breathalyzer/lib/lib.mligo" "Breath"
#import "./util.mligo" "Util"
#import "../src/airdrop.mligo" "Airdrop"

let dummy_metadata = 0x01

(* Fixture tree, over the four drops of docs/10-Sandbox-Sample-Data.md, with
   the leaves of the current getLeaf() (see infra/scripts/merkle.ts):
   root 0xce2ca122…, generated by `npm run make:proof`-style code:
   buildTree(drops) and getProof(drops, index). *)
let merkle_root = 0xce2ca1226de039dd82f7dee62d8d17896bc9dc352b6ca705b0c7ac2431407d0d

let claimer = ("tz1WbpqNj8Pg9dbz1v8nJo9ofAHGGPQAcXTM" : address)

let claimer_amount = 39n

(* getProof(drops, 1): the first step is a right one, the second a left one *)
let claimer_proof =
  [
    (0x11d493116efc9abebcdb30c7df8d41f0f2d80bb73348eb7dd4a2ae99c7a62b2c, false);
    (0x23b9ad2635bab6a413a847cee949c20abd17bff89576a9020d553dde2401d3f3, true)
  ]

let dummy_token = (("KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton" : address), 1n)

let case_happy_path =
  Breath.Model.case
    "claim"
    "An happy path when someone claim"
    (fun (level : Breath.Logger.level) -> let (baker, (alice, _, _)) =
         Breath.Context.init_default () in
       let () = Breath.Logger.log level "Initialize Token with 300 to Alice" in
       let token =
         Breath.Context.act_as
           baker
           (Util.originate_token level alice.address 0n 300n) in
       let () = Breath.Logger.log level "Initialize Airdrop" in
       let airdrop =
         Breath.Context.act_as
           baker
           (Util.originate_airdrop
              level
              dummy_metadata
              (token.originated_address, 0n)
              merkle_root
              (Big_map.empty : Airdrop.Storage.claimed)) in
       let () = Breath.Logger.log level "Alice transfers 200 to Airdrop" in
       let alice_action_1 =
         Breath.Context.act_as
           alice
           (Util.request_token_transfer
              token
              ([
                 ({
                   from_ = alice.address;
                   txs =
                     ([
                        {
                         to_ = airdrop.originated_address;
                         amount = 200n;
                         token_id = 0n
                        }
                      ])
                   })
                ])) in
       let () = Breath.Logger.log level "Claim Airdrop" in
       let alice_action_2 =
         Breath.Context.act_as
           alice
           (Util.request_claim
              airdrop
              (Claim
                 ({
                   addr = claimer;
                   amnt = claimer_amount;
                   merkle_proof = claimer_proof
                 }))) in
       Breath.Result.reduce
         [
           alice_action_1;
           alice_action_2;
           Util.expected_airdrop_state
             airdrop
             (Big_map.literal [(claimer, unit)])
             0mutez
         ])

let case_nohappy_path =
  Breath.Model.case
    "already claimed"
    "Already claimed when someone claim"
    (fun (level : Breath.Logger.level) -> let (operator, (alice, _, _)) =
         Breath.Context.init_default () in
       let () = Breath.Logger.log level "Initialize Airdrop" in
       let airdrop =
         Breath.Context.act_as
           operator
           (Util.originate_airdrop
              level
              dummy_metadata
              dummy_token
              merkle_root
              (Big_map.literal [(claimer, unit)])) in
       let () = Breath.Logger.log level "Claim Airdrop" in
       let alice_action_1 =
         Breath.Context.act_as
           alice
           (Util.request_claim
              airdrop
              (Claim
                 ({
                   addr = claimer;
                   amnt = claimer_amount;
                   merkle_proof = claimer_proof
                 }))) in
       Breath.Result.reduce
         [
           Breath.Expect.fail_with_message "ALREADY_CLAIMED" alice_action_1;
           Util.expected_airdrop_state
             airdrop
             (Big_map.literal [(claimer, unit)])
             0mutez
         ])

let case_invalid_proof =
  Breath.Model.case
    "invalid proof"
    "A claim with a proof pointing the wrong way is rejected"
    (fun (level : Breath.Logger.level) -> let (operator, (alice, _, _)) =
         Breath.Context.init_default () in
       let () = Breath.Logger.log level "Initialize Airdrop" in
       let airdrop =
         Breath.Context.act_as
           operator
           (Util.originate_airdrop
              level
              dummy_metadata
              dummy_token
              merkle_root
              (Big_map.empty : Airdrop.Storage.claimed)) in
       let () = Breath.Logger.log level "Claim Airdrop" in
       (* same proof as the happy path, with the first flag flipped *)
       let alice_action_1 =
         Breath.Context.act_as
           alice
           (Util.request_claim
              airdrop
              (Claim
                 ({
                   addr = claimer;
                   amnt = claimer_amount;
                   merkle_proof =
                     [
                       (0x11d493116efc9abebcdb30c7df8d41f0f2d80bb73348eb7dd4a2ae99c7a62b2c, true);
                       (0x23b9ad2635bab6a413a847cee949c20abd17bff89576a9020d553dde2401d3f3, true)
                     ]
                 }))) in
       Breath.Result.reduce
         [
           Breath.Expect.fail_with_message "INVALID_PROOF" alice_action_1;
           Util.expected_airdrop_state
             airdrop
             (Big_map.empty : Airdrop.Storage.claimed)
             0mutez
         ])

let suite =
  Breath.Model.suite
    "Suite for [Airdrop]"
    [case_happy_path; case_nohappy_path; case_invalid_proof]
