#!/bin/bash

# run a local tezos sandbox
# https://tezos.gitlab.io/flextesa/

image=oxheadalpha/flextesa:20221123
script=limabox
docker run --rm --name sandbox --detach -p 20000:20000 \
       -e block_time=3 \
       -e flextesa_node_cors_origin='*' \
       "$image" "$script" start

sleep 10 ;

# originate a token contract
docker exec -it sandbox octez-client originate contract token \
  transferring 0 from alice running "$(cat tests/testdata/token.tz)" \
  --init "$(cat tests/testdata/token_storage.tz)" --burn-cap 0.62175

# extract token address
token=$(docker exec -it sandbox octez-client list known contracts | head -n 1 | awk -F':' '{print $2}' | tr -d '\r' | xargs)

# update .env with token address
sed "s/TOKEN_CONTRACT=.*/TOKEN_CONTRACT=$token/g" -i ../web/.env
